### ISSUE TITLE
Support string substitution in Helm charts

### ISSUE THREAD

**Issue by NiklasRosenstein** [helsing-ai/nyl#1]
Nyl string substitution currently only works on top-level manifests that are fed directly to Nyl. It would however be quite convenient if a Helm chart referenced by Nyl could benefit from Nyl's string substition, for example to generate random passwords to pass into a `nyl.io/StatefulSecret` (which can already be generated in a Helm chart).

For example:

```yaml
apiVersion: nyl.io/v1
kind: StatefulSecret
metadata:
  name: argocd-admin
  namespace: argocd
stringData:
  password: ${{ bcrypt(random_password(length=24)) }}
```

This resource currently _must_ live outside of any Helm chart because Helm complains about the syntax.

There are two ways to go about this:

1. Pre-process the chart; this has the disadvantage that it's still in unstructured form so it will be tricky to run through `structed-templates`
2. Post-process the chart's generated resources; however this requires escaping for Helm to not complain about the syntax

**Comment by NiklasRosenstein** [comment]
Actually the syntax is not _too_ ugly..

```yaml
apiVersion: nyl.io/v1
kind: StatefulSecret
metadata:
  name: argocd-admin
  namespace: argocd
stringData:
  password: {{`${{ bcrypt(random_password(length=24)) }}`}}
```
