### ISSUE TITLE
Implement `StatefulSecret` resource

### ISSUE THREAD

**Issue by NiklasRosenstein** [helsing-ai/nyl#2]
Nyl's `StatefulSecret` resource should be a tool to generate a Kubernetes secret but retaining any existing values for known keys of the secret. This way, the secret becomes stateful in that the Nyl-generated manifests will not override the existing secret value.

Example:

```yaml
apiVersion: nyl.io/v1
kind: StatefulSecret
metadata:
  name: argocd-admin
  namespace: argocd
stringData:
  password: foobar
```

This would generate the following Kubernetes secret:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: argocd-admin
  namespace: argocd
stringData:
  password: foobar
```

If the Kubernetes secret was created and we then changed the `StatefulSecret`'s `password` field to another value, the generated `Secret` would still contain the same password from the current state of the secret in the cluster.
