### ISSUE TITLE
Add check to ensure ArgoCD application created with Nyl doesn't point to a likely incorrect namespace

### ISSUE THREAD

**Issue by NiklasRosenstein** [helsing-ai/nyl#21]
When creating ArgoCD applications with Nly, a pattern I've found useful so far is to create the namespace and application in one file:

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: backstage

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
spec:
  project: default
  sources:
  - path: charts/backstage
    repoURL: https://gitlab.example.com/gitops/main.git
    targetRevision: HEAD
    helm:
      valuesObject:
        host: backstage.local
        secretName: backstage
  destination:
    server: "https://kubernetes.default.svc"
    namespace: backstage
```

Nyl should check if the `destination.namespace` really is the one being referenced here (only if the  `server` is `kubernetes.default.svc`)
