### ISSUE TITLE
Implement `lookup()` template function to reference other Kubernetes resources

### ISSUE THREAD

**Issue by NiklasRosenstein** [helsing-ai/nyl#3]
The `ref()` template function should allow to reference other Kubernetes resources, particularly secrets, to read data from them at templating time. This implies a kind of dependency graph between the resources, requiring that resources that depend on other, not-yet-existent resources must not be generated until the dependency is satisfied.

An example use case for this is to generate a `StatefulSecret` and then reference the value in a `HelmChart`'s value when the chart does not offer a seam to inject the actual secret.

Example:

```yaml
apiVersion: nyl.io/v1
kind: StatefulSecret
metadata:
  name: my-password
stringData:
  password: {{`${{ bcrypt(random_password(length=24)) }}`}}

---

apiVersion: nyl.io/v1
kind: HelmChart
name: {{ .Release.Name }}-app
chart: # ...
values:
  structuredConfig:
    password: {{`${{ b64decode(ref("secrets", "my-password", "data.password")) }}`}}
```

**Comment by NiklasRosenstein** [comment]
Looks like Helm already has that feature 🤔  It's called `lookup()`

https://stackoverflow.com/a/64325744

**Comment by NiklasRosenstein** [comment]
Example usage:

```yaml
---
apiVersion: inline.nyl.io/v1
kind: HelmChart
release:
  name: immich-db
  namespace: default
chart:
  path: "@charts/postgres-db"
values:
  instances: 1
  s3_backup:
    enabled: true
    endpoint: ${{ secrets.get("fracture.cnpg-backups.endpoint") }}
    bucket: ${{ secrets.get("fracture.cnpg-backups.bucket") }}
    access_key: ${{ secrets.get("fracture.cnpg-backups.access_key") }}
    secret_key: ${{ secrets.get("fracture.cnpg-backups.secret_key") }}

---
apiVersion: inline.nyl.io/v1
kind: HelmChart
release:
  name: immich-storj
  namespace: default
chart:
  path: '@charts/immich-csi-s3'
values:
  domain: immich-storj.rosenstein.app
  storageClassName: csi-s3-storj
  dbUrl: ${{ b64decode(ref("v1", "Secret", "immich-db-app", "default").data.uri) }}?sslmode=no-verify
```
