### ISSUE TITLE
Add template function to hash a resource in the same manifest

### ISSUE THREAD

**Issue by NiklasRosenstein** [helsing-ai/nyl#32]
This would be very useful to generate a typical "config hash" label that can be used to rotate Pods in a deployment when another resource, usually a Secret or ConfigMap, changes.

```yaml
apiVersion: apps/v1
kind: Deployment
# ...
spec:
  template:
    metadata:
      labels:
        confighash: ${{ hash(local_lookup("v1", "Secret", "mysecret", "namespace").data) }}
  # ...
```
