### ISSUE TITLE
Applying a Kyverno policy with the `PostProcessor` resource that modifies the namespace of a resource will duplicate it

### ISSUE THREAD

**Issue by NiklasRosenstein** [helsing-ai/nyl#51]
If you modify the namespace of a resource with a Kyverno policy using the `inline.nyl.io/v1/PostProcessor` resource, it will end up duplicating it. For example:

```yaml
# test.yaml
---
apiVersion: inline.nyl.io/v1
kind: PostProcessor
spec:
  kyverno:
    inlinePolicies:
      fix-role-binding-namespace:
        apiVersion: kyverno.io/v1
        kind: ClusterPolicy
        metadata:
          name: fix-role-binding-namespace
        spec:
          rules:
          - name: fix-role-binding-namespace
            match:
              any:
              - resources:
                  kinds:
                  - RoleBinding
            mutate:
              patchStrategicMerge:
                metadata:
                  namespace: foobar

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-rolebinding
  namespace: spam
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: test-role
subjects:
- kind: ServiceAccount
  name: test
```

Running `nyl template test.yaml` gives:

```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-rolebinding
  namespace: spam
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: test-role
subjects:
- kind: ServiceAccount
  name: test

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-rolebinding
  namespace: foobar
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: test-role
subjects:
- kind: ServiceAccount
  name: test
```

This is because the `PostProcessor` treats the apiVersion/kind/namespace/name as the identity of the resource and hence not replace the previous one since a resource with a new identity is loaded after applying the policy.

**Comment by NiklasRosenstein** [comment]
This should be fixed as part of 0b63622 and bumping our min Kyverno dependency to 1.13.x (where Kyverno outputs all resources instead of just mutated ones). We no longer need to generate a unique ID for each resource and map Kyverno's outputs to the old resources.

Running `nyl template` on the above example now correctly results in:

```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-rolebinding
  namespace: foobar
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: test-role
subjects:
- kind: ServiceAccount
  name: test
```
