### ISSUE TITLE
Namespaced but namespace-less resources produced by `HelmChart` resource does not inherit parent resource namespace

### ISSUE THREAD

**Issue by NiklasRosenstein** [helsing-ai/nyl#56]
When instantiation a Helm chart with Nyl:

```yaml
apiVersion: inline.nyl.io/v1
kind: HelmChart
metadata:
  name: foo
  namespace: bar
spec:
  chart: # ...
  values: # ...
```

which produces a resource like

```yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}  # will be foo
spec: # ...
```

The `HelmChart` will be replaced with the generated `Service` resource without a namespace, when it should instead inherit the `HelmChart` resource's namespace. Otherwise, you loose some control over the namespace that resources are placed in (esp. if you don't own the Helm chart that you instantiate) and the default namespace that Nyl will assume for the resource is not correct (either the only `Namespace` resource in the manifest, or the name of the manifest file).
